"""
COMAF-Lite → Mathematica (Wolfram Language) Transpiler
Converts a ProgramNode AST into a .wl Wolfram Language file.
"""

from typing import List
from ..ast import (ProgramNode, StateBlockNode, EntropyBlockNode,
                   GeometryBlockNode, StabilityBlockNode, CollapseBlockNode,
                   WarpBlockNode, EmitBlockNode, TransitionBlockNode,
                   AssignmentNode, PhysicsQuantityNode, Node)


PNMS_HEADER = r"""(* === PNMS Constants (auto-generated by COMAF-Lite transpiler) === *)
\[HBar] = Quantity["ReducedPlanckConstant"];
h = 2 Pi \[HBar];
c = Quantity["SpeedOfLight"];
GN = Quantity["GravitationalConstant"];
kB = Quantity["BoltzmannConstant"];

\[Lambda]P = Sqrt[\[HBar] GN / c^3];
tP = Sqrt[\[HBar] GN / c^5];
EP = Sqrt[\[HBar] c^5 / GN];
mP = Sqrt[\[HBar] c / GN];
TP = EP / kB;

Plameter = 10^35 \[Lambda]P;
Plasecond = 10^44 tP;
Plajoule = 10^9 EP;
Plakilogram = 10^8 mP;
WarpTick = 10^61 tP;
Quasiplanck = 10^61 \[Lambda]P;

(* E_jump function *)
Leff[v_, L0_: Plameter, \[Alpha]_: 2] := L0 (1 - v^2/c^2)^\[Alpha];
\[CapitalPsi][v_] := \[Lambda]P / Leff[v];
Ejump[v_] := h / \[Lambda]P (1 - Exp[-\[CapitalPsi][v]]);

(* Decoherence metric *)
Dcoh[gradS_, t_] := Exp[-Abs[gradS] t];
"""


class MathematicaTranspiler:
    def __init__(self, program: ProgramNode):
        self.program = program
        self.lines: List[str] = []

    def transpile(self) -> str:
        self.lines = []
        self._emit_header()
        self._emit_metadata()
        self._emit_blocks()
        return "\n".join(self.lines)

    def _emit(self, line: str = ""):
        self.lines.append(line)

    def _emit_header(self):
        self._emit(PNMS_HEADER)

    def _emit_metadata(self):
        p = self.program
        self._emit(f'(* === Model Metadata === *)')
        if p.model_name:
            self._emit(f'modelName = "{p.model_name}";')
        self._emit(f'entityName = "{p.entity}";')
        self._emit(f'cycleID = "{p.cycle}";')
        self._emit(f'frameRange = "{p.frame}";')
        self._emit(f'units = "{p.units}";')
        self._emit()

    def _emit_blocks(self):
        for block in self.program.blocks:
            self._emit_block(block)

    def _emit_block(self, block: Node):
        if isinstance(block, StateBlockNode):
            self._emit_state(block)
        elif isinstance(block, EntropyBlockNode):
            self._emit_entropy(block)
        elif isinstance(block, GeometryBlockNode):
            self._emit_geometry(block)
        elif isinstance(block, StabilityBlockNode):
            self._emit_stability(block)
        elif isinstance(block, CollapseBlockNode):
            self._emit_collapse(block)
        elif isinstance(block, WarpBlockNode):
            self._emit_warp(block)
        elif isinstance(block, EmitBlockNode):
            self._emit_emit(block)
        elif isinstance(block, TransitionBlockNode):
            self._emit_transition(block)
        elif isinstance(block, PhysicsQuantityNode):
            self._emit_physics_quantity(block)

    def _emit_state(self, b: StateBlockNode):
        self._emit(f"(* STATE {b.name} *)")
        init = b.init
        if isinstance(init, dict) and "superposition" in init:
            states = init["superposition"]
            coeffs = [f"1/Sqrt[{len(states)}]" for _ in states]
            terms = " + ".join(
                f"{c} {s.replace('|', '').replace('⟩', '')}State[t]"
                for c, s in zip(coeffs, states)
            )
            self._emit(f"{b.name}[t_] := {terms};")
        else:
            name_clean = str(init).replace("|", "").replace("⟩", "") if init else "0"
            self._emit(f"{b.name}[t_] := {name_clean}State[t];  (* init: {init} *)")
        self._emit(f"H{b.name}[t_] := {b.hamiltonian};  (* Hamiltonian *)")
        self._emit()

    def _emit_entropy(self, b: EntropyBlockNode):
        self._emit(f"(* ENTROPY {b.name} *)")
        self._emit(f"S0{b.name} = {b.init};")
        self._emit(f"Smax{b.name} = {b.max_val};")
        self._emit(rf"\[Tau]{b.name} = {b.scale} Plasecond;  (* {b.scale_unit} *)")
        self._emit(rf"{b.name}[t_] := S0{b.name} Exp[-t/\[Tau]{b.name}] + Smax{b.name} (1 - Exp[-t/\[Tau]{b.name}]);")
        self._emit()

    def _emit_geometry(self, b: GeometryBlockNode):
        self._emit(f"(* GEOMETRY *)")
        self._emit(f"(* Field equation: {b.field_equation} *)")
        self._emit(r"(* G\[Mu]\[Nu] + \[CapitalLambda] g\[Mu]\[Nu] = (8\[Pi] GN / c^4) <<T\[Mu]\[Nu]>> *)")
        self._emit()

    def _emit_stability(self, b: StabilityBlockNode):
        self._emit(f"(* STABILITY metric {b.metric_name} *)")
        expr = b.expression.replace("exp", "Exp").replace("∇", "D[").replace("|", "Abs[")
        self._emit(f"(* {b.metric_name}[gradS_, t_] := Exp[-Abs[gradS] t] *)")
        self._emit(f"{b.metric_name}[gradS_, t_] := Dcoh[gradS, t];")
        self._emit()

    def _emit_collapse(self, b: CollapseBlockNode):
        self._emit(f"(* COLLAPSE block — condition: {b.condition} *)")
        cond = self._translate_condition(b.condition)
        energy_line = f"collapseEnergy = Ejump[v];" if b.energy else ""
        res_line = r"resolution = \[Lambda]P;" if b.resolution else ""
        self._emit(f"collapseQ[v_, t_] := {cond};")
        self._emit(f"If[collapseQ[v, t],")
        self._emit(f"  {energy_line}")
        self._emit(f"  {res_line}")
        self._emit(f"];")
        self._emit()

    def _emit_warp(self, b: WarpBlockNode):
        self._emit(f"(* WARP block — condition: {b.condition} *)")
        cond = self._translate_condition(b.condition)
        vel = b.velocity if b.velocity else r"c Exp[\[Kappa] R]"
        self._emit(f"warpQ[R_, t_] := {cond};")
        self._emit(f"If[warpQ[R, t],")
        self._emit(f"  vWarp = {vel};  (* target: {b.target} *)")
        self._emit(f"];")
        self._emit()

    def _emit_emit(self, b: EmitBlockNode):
        self._emit(f"(* EMIT block — condition: {b.condition} *)")
        cond = self._translate_condition(b.condition)
        self._emit(f"emitQ := {cond};")
        self._emit(f"If[emitQ,")
        self._emit(f"  emitEnergy = {b.energy};  (* decay: {b.decay} *)")
        self._emit(f"];")
        self._emit()

    def _emit_transition(self, b: TransitionBlockNode):
        self._emit(f"(* ON {b.event_name} *)")
        self._emit(f"WhenEvent[t == tEnd, {{")
        for stmt in b.statements:
            self._emit(f"  (* {stmt} *)")
        self._emit(f"}}];")
        self._emit()

    def _emit_physics_quantity(self, b: PhysicsQuantityNode):
        unit_comment = f"  (* unit: {b.unit} *)" if b.unit else ""
        self._emit(f"(* {b.keyword} {b.name} *)")
        self._emit(f"{b.name}[t_] := {b.expression};{unit_comment}")
        self._emit()

    def _translate_condition(self, condition: str) -> str:
        """Translate COMAF-Lite condition syntax to Mathematica."""
        c = condition
        c = c.replace("L_eff(v)", "Leff[v]")
        c = c.replace("λ_P", r"\[Lambda]P")
        c = c.replace("lambda_p", r"\[Lambda]P")
        c = c.replace("D(t)", "Dcoh[gradS, t]")
        c = c.replace("AND", "&&")
        c = c.replace("OR", "||")
        c = c.replace("NOT ", "!")
        return c


def transpile_mathematica(program: ProgramNode) -> str:
    """Transpile a ProgramNode to Wolfram Language (.wl) source."""
    return MathematicaTranspiler(program).transpile()
