"""
COMAF-Lite → Python (NumPy/SciPy) Transpiler
Converts a ProgramNode AST into a Python simulation script.
"""

from typing import List
from ..ast import (ProgramNode, StateBlockNode, EntropyBlockNode,
                   GeometryBlockNode, StabilityBlockNode, CollapseBlockNode,
                   WarpBlockNode, EmitBlockNode, TransitionBlockNode,
                   PhysicsQuantityNode, Node)


PYTHON_HEADER = """\
\"\"\"
Auto-generated COMAF-Lite model — Python/NumPy backend.
Generated by COMAF-Lite transpiler v0.1.

Runs standalone — only numpy and scipy required:
    pip install numpy scipy
    python {model_name}.py
\"\"\"
import math
import numpy as np
from scipy.integrate import solve_ivp

# ── PNMS constants (inlined from comaf.pnms — no comaf package required) ─────
HBAR      = 1.054571817e-34        # J·s
H_PLANCK  = 6.62607014594008e-34   # J·s
C         = 299792458.0            # m/s
G_NEWTON  = 6.6743e-11             # m³ kg⁻¹ s⁻²
K_B       = 1.380649e-23           # J/K
LAMBDA_P  = 1.61625502392855e-35   # m  (Planck length)
T_P       = 5.391246446661944e-44  # s  (Planck time)
E_P       = 1.956081636e+09        # J  (Planck energy ≈ 2 GJ)
M_P       = 2.176434342051127e-08  # kg (Planck mass)
PLASECOND = 5.3912464466619445     # s  (1 Plasecond ≈ 5.39 s)
WARPTICK  = 5.391246446661943e+17  # s  (1 WarpTick ≈ 17.1 Gyr)
PLAMETER  = 1.6162550239285498     # m  (1 Plameter ≈ 1.616 m)

def l_eff(v, l0=PLAMETER, alpha=2.0):
    \"\"\"Effective rendering length at velocity v.\"\"\"
    if abs(v) >= C:
        return LAMBDA_P
    return l0 * (1 - (v / C) ** 2) ** alpha

def psi_factor(v, l0=PLAMETER, alpha=2.0):
    \"\"\"Planck-state transition factor.\"\"\"
    leff = l_eff(v, l0, alpha)
    return LAMBDA_P / leff if leff > 0 else float('inf')

def e_jump(v, l0=PLAMETER, alpha=2.0):
    \"\"\"Energy for a quantum jump at velocity v.\"\"\"
    psi = psi_factor(v, l0, alpha)
    return (H_PLANCK / LAMBDA_P) * (1 - math.exp(-min(psi, 700)))

def decoherence_metric(grad_s, t):
    \"\"\"D(t) = exp(-|grad_S| * t).\"\"\"
    return math.exp(-abs(grad_s) * t)

def f_collapse(v, lambda_cosmo, r, l0=PLAMETER, alpha=2.0):
    \"\"\"Rendering collapse function.\"\"\"
    leff = l_eff(v, l0, alpha)
    theta = 1.0 if leff < LAMBDA_P else 0.0
    ejump = e_jump(v, l0, alpha)
    return theta * (ejump / E_P) * math.exp(-lambda_cosmo * r)

"""


class PythonTranspiler:
    def __init__(self, program: ProgramNode):
        self.program = program
        self.lines: List[str] = []

    def transpile(self) -> str:
        self.lines = []
        self._emit(PYTHON_HEADER)
        self._emit_metadata()
        self._emit_blocks()
        self._emit_main()
        return "\n".join(self.lines)

    def _emit(self, line: str = ""):
        self.lines.append(line)

    def _emit_metadata(self):
        p = self.program
        self._emit("# === Model Metadata ===")
        if p.model_name:
            self._emit(f'MODEL_NAME = "{p.model_name}"')
        self._emit(f'ENTITY = "{p.entity}"')
        self._emit(f'CYCLE_ID = "{p.cycle}"')
        self._emit(f'FRAME = "{p.frame}"')
        self._emit(f'UNITS = "{p.units}"')
        self._emit()

    def _emit_blocks(self):
        for block in self.program.blocks:
            self._emit_block(block)

    def _emit_block(self, block):
        if isinstance(block, EntropyBlockNode):
            self._emit_entropy(block)
        elif isinstance(block, StabilityBlockNode):
            self._emit_stability(block)
        elif isinstance(block, CollapseBlockNode):
            self._emit_collapse(block)
        elif isinstance(block, WarpBlockNode):
            self._emit_warp(block)
        elif isinstance(block, TransitionBlockNode):
            self._emit_transition(block)
        elif isinstance(block, PhysicsQuantityNode):
            self._emit_physics_quantity(block)

    def _emit_entropy(self, b: EntropyBlockNode):
        self._emit(f"# ENTROPY {b.name}")
        self._emit(f"S0_{b.name} = {b.init}")
        self._emit(f"Smax_{b.name} = {b.max_val}")
        self._emit(f"tau_{b.name} = {b.scale} * PLASECOND  # {b.scale_unit}")
        self._emit(f"")
        self._emit(f"def entropy_{b.name}(t):")
        self._emit(f"    return S0_{b.name} * np.exp(-t / tau_{b.name}) + Smax_{b.name} * (1 - np.exp(-t / tau_{b.name}))")
        self._emit()

    def _emit_stability(self, b: StabilityBlockNode):
        self._emit(f"# STABILITY: {b.metric_name}")
        self._emit(f"def {b.metric_name}(grad_s, t):")
        self._emit(f"    return np.exp(-np.abs(grad_s) * t)")
        self._emit()

    def _emit_collapse(self, b: CollapseBlockNode):
        self._emit(f"# COLLAPSE: {b.condition}")
        self._emit(f"def collapse_check(v, t):")
        self._emit(f"    return l_eff(v) < LAMBDA_P")
        self._emit()

    def _emit_warp(self, b: WarpBlockNode):
        self._emit(f"# WARP: {b.condition}")
        self._emit(f"def warp_velocity(R, kappa=0.001):")
        self._emit(f"    return C * np.exp(kappa * R)")
        self._emit()

    def _emit_transition(self, b: TransitionBlockNode):
        self._emit(f"# TRANSITION ON {b.event_name}")
        self._emit(f"def on_{b.event_name.replace('.', '_')}(S, psi, alpha=7.2973525693e-3):")
        for stmt in b.statements:
            self._emit(f"    # {stmt}")
        self._emit(f"    return S / (1 + alpha), psi")
        self._emit()

    def _emit_physics_quantity(self, b: PhysicsQuantityNode):
        import re as _re
        unit_comment = f"  # unit: {b.unit}" if b.unit else ""
        kw_lower = b.keyword.lower()
        self._emit(f"# {b.keyword} {b.name}{unit_comment}")
        # Translate math tokens to numpy equivalents (handle spaces from parser)
        expr = b.expression
        expr = _re.sub(r'cos\s*\(', 'np.cos(', expr)
        expr = _re.sub(r'sin\s*\(', 'np.sin(', expr)
        expr = _re.sub(r'exp\s*\(', 'np.exp(', expr)
        expr = expr.replace("^", "**")
        self._emit(f"def {kw_lower}_{b.name}(t):")
        self._emit(f"    return {expr if expr else 'None'}")
        self._emit()

    def _emit_main(self):
        # Find entropy block for ODE constants (fallback to literals if absent)
        entropy_block = next(
            (b for b in self.program.blocks if isinstance(b, EntropyBlockNode)), None
        )
        s_init = f"S0_{entropy_block.name}" if entropy_block else "1.0"
        s_max  = f"Smax_{entropy_block.name}" if entropy_block else "1.0"
        tau    = f"tau_{entropy_block.name}" if entropy_block else "WARPTICK"

        self._emit('if __name__ == "__main__":')
        self._emit(f'    print(f"Model: {{{self.program.entity!r}}}, Cycle: {{{self.program.cycle!r}}}")')
        self._emit(f'    S_MAX   = {s_max}')
        self._emit(f'    TAU     = {tau}')
        self._emit(f'    S_INIT  = {s_init}')
        self._emit(f'    ALPHA_D = 1e-9  # decoherence coupling upper bound (BEC data)')
        self._emit(f'    GRAD_S  = 1.0   # entropy gradient (PNMS units)')
        self._emit(f'    # Simulate 10 time constants in Plaseconds (use comaf simulate for full run)')
        self._emit(f'    _t_end = 10 * TAU / PLASECOND  # 10τ in Plaseconds')
        self._emit(f'    t_span = (0, _t_end)')
        self._emit(f'    t_eval = np.linspace(0, _t_end, 200)')
        self._emit()
        self._emit(f'    def odes(t, y):')
        self._emit(f'        S, D = y')
        self._emit(f'        dS_dt = (S_MAX - S) / (TAU / PLASECOND)')
        self._emit(f'        dD_dt = -ALPHA_D * GRAD_S * D')
        self._emit(f'        return [dS_dt, dD_dt]')
        self._emit()
        self._emit(f'    y0 = [S_INIT, 1.0]')
        self._emit(f'    sol = solve_ivp(odes, t_span, y0, t_eval=t_eval, method="RK45")')
        self._emit(f'    print(f"  t=0:    S={{sol.y[0][0]:.4e}}  D={{sol.y[1][0]:.6f}}")')
        self._emit(f'    print(f"  t=5τ:   S={{sol.y[0][len(sol.t)//2]:.4e}}  D={{sol.y[1][len(sol.t)//2]:.6f}}")')
        self._emit(f'    print(f"  t=10τ:  S={{sol.y[0][-1]:.4e}}  D={{sol.y[1][-1]:.6f}}")')
        self._emit(f'    import os')
        self._emit(f'    if not os.environ.get("COMAF_NO_PLOT"):')
        self._emit(f'        try:')
        self._emit(f'            import matplotlib.pyplot as plt')
        self._emit(f'            plt.plot(sol.t, sol.y[0], label="S(t)")')
        self._emit(f'            plt.plot(sol.t, sol.y[1], label="D(t)")')
        self._emit(f'            plt.xlabel("Time (Plaseconds)"); plt.ylabel("Value")')
        self._emit(f'            plt.legend(); plt.show()')
        self._emit(f'        except ImportError:')
        self._emit(f'            print("  (matplotlib not installed — set COMAF_NO_PLOT=1 to suppress)")')


def transpile_python(program: ProgramNode) -> str:
    """Transpile a ProgramNode to Python/NumPy source."""
    return PythonTranspiler(program).transpile()
