"""
COMAF-Lite → Python (NumPy/SciPy) Transpiler
Converts a ProgramNode AST into a Python simulation script.
"""

from typing import List
from ..ast import (ProgramNode, StateBlockNode, EntropyBlockNode,
                   GeometryBlockNode, StabilityBlockNode, CollapseBlockNode,
                   WarpBlockNode, EmitBlockNode, TransitionBlockNode, Node)


PYTHON_HEADER = """\
\"\"\"
Auto-generated COMAF-Lite model — Python/NumPy backend.
Generated by COMAF-Lite transpiler v0.1.
\"\"\"
import numpy as np
from scipy.integrate import solve_ivp
from comaf.pnms import (
    LAMBDA_P, T_P, E_P, M_P, C, K_B,
    PLASECOND, WARPTICK, PLAMETER,
    l_eff, psi_factor, e_jump, decoherence_metric, f_collapse
)

"""


class PythonTranspiler:
    def __init__(self, program: ProgramNode):
        self.program = program
        self.lines: List[str] = []

    def transpile(self) -> str:
        self.lines = []
        self._emit(PYTHON_HEADER)
        self._emit_metadata()
        self._emit_blocks()
        self._emit_main()
        return "\n".join(self.lines)

    def _emit(self, line: str = ""):
        self.lines.append(line)

    def _emit_metadata(self):
        p = self.program
        self._emit("# === Model Metadata ===")
        if p.model_name:
            self._emit(f'MODEL_NAME = "{p.model_name}"')
        self._emit(f'ENTITY = "{p.entity}"')
        self._emit(f'CYCLE_ID = "{p.cycle}"')
        self._emit(f'FRAME = "{p.frame}"')
        self._emit(f'UNITS = "{p.units}"')
        self._emit()

    def _emit_blocks(self):
        for block in self.program.blocks:
            self._emit_block(block)

    def _emit_block(self, block):
        if isinstance(block, EntropyBlockNode):
            self._emit_entropy(block)
        elif isinstance(block, StabilityBlockNode):
            self._emit_stability(block)
        elif isinstance(block, CollapseBlockNode):
            self._emit_collapse(block)
        elif isinstance(block, WarpBlockNode):
            self._emit_warp(block)
        elif isinstance(block, TransitionBlockNode):
            self._emit_transition(block)

    def _emit_entropy(self, b: EntropyBlockNode):
        self._emit(f"# ENTROPY {b.name}")
        self._emit(f"S0_{b.name} = {b.init}")
        self._emit(f"Smax_{b.name} = {b.max_val}")
        self._emit(f"tau_{b.name} = {b.scale} * PLASECOND  # {b.scale_unit}")
        self._emit(f"")
        self._emit(f"def entropy_{b.name}(t):")
        self._emit(f"    return S0_{b.name} * np.exp(-t / tau_{b.name}) + Smax_{b.name} * (1 - np.exp(-t / tau_{b.name}))")
        self._emit()

    def _emit_stability(self, b: StabilityBlockNode):
        self._emit(f"# STABILITY: {b.metric_name}")
        self._emit(f"def {b.metric_name}(grad_s, t):")
        self._emit(f"    return np.exp(-np.abs(grad_s) * t)")
        self._emit()

    def _emit_collapse(self, b: CollapseBlockNode):
        self._emit(f"# COLLAPSE: {b.condition}")
        self._emit(f"def collapse_check(v, t):")
        self._emit(f"    return l_eff(v) < LAMBDA_P")
        self._emit()

    def _emit_warp(self, b: WarpBlockNode):
        self._emit(f"# WARP: {b.condition}")
        self._emit(f"def warp_velocity(R, kappa=0.001):")
        self._emit(f"    return C * np.exp(kappa * R)")
        self._emit()

    def _emit_transition(self, b: TransitionBlockNode):
        self._emit(f"# TRANSITION ON {b.event_name}")
        self._emit(f"def on_{b.event_name.replace('.', '_')}(S, psi, alpha=7.2973525693e-3):")
        for stmt in b.statements:
            self._emit(f"    # {stmt}")
        self._emit(f"    return S / (1 + alpha), psi")
        self._emit()

    def _emit_main(self):
        self._emit('if __name__ == "__main__":')
        self._emit('    import matplotlib.pyplot as plt')
        self._emit(f'    t_span = (0, WARPTICK)')
        self._emit(f'    t_eval = np.linspace(0, WARPTICK, 1000)')
        self._emit(f'    print(f"Model: {{{self.program.entity!r}}}, Cycle: {{{self.program.cycle!r}}}")')
        self._emit(f'    print("Simulation ready. Implement ODE system and call solve_ivp.")')


def transpile_python(program: ProgramNode) -> str:
    """Transpile a ProgramNode to Python/NumPy source."""
    return PythonTranspiler(program).transpile()
